name: tests
on:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.x']
    steps:
    - name: check out source
      uses: actions/checkout@v2
    - name: set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: build and test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir ~/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
          chmod 600 ~/.gem/credentials
      - run: gem build rich-text.gemspec
      - run: gem push --key github --host https://rubygems.pkg.github.com/feedbackfruits rich-text-*.gem
